### ISSUE TITLE
[BUG] Unsupported Device/Browser

### ISSUE THREAD

**Issue by seonwoolee** [hmlendea/gfn-electron#138]
### Describe the bug

Upon launch, I get an error saying unsupported device/browser.

### To Reproduce

1. Install on Arch Linux via the [AUR package](https://aur.archlinux.org/packages/geforcenow-electron)
2. Launch GeForce Now
3. Observe error about an unsupported device/browser

### Screenshots

![Screenshot_2022-05-17_16-50-09](https://user-images.githubusercontent.com/39072252/168907710-6b26f1eb-dfcf-4036-b2a4-6619a5843855.png)

### Operatingsystem

Arch Linux

### Desktop Environment

XFCE

### Installation method

AUR

### Version

1.7.0-1

**Comment by hmlendea** [comment]
Is this a fresh install of the app or an update from a past version?
Did this appear spontaneously or upon installation / updating the version?

**Comment by seonwoolee** [comment]
This is a fresh install and this error appears on first run. I'm using X11

**Comment by seonwoolee** [comment]
Any ideas?

**Comment by Skullfurious** [comment]
The application will not work with Google sign-in.

![image](https://user-images.githubusercontent.com/34455502/172065166-d3535245-4df1-4b8d-9f31-d85c26fdff0f.png)

The issue is present for any unofficial browser port that tries to log in to google services using only an email and password. 

Official Page: https://support.google.com/accounts/answer/6010255#zippy=

**Comment by seonwoolee** [comment]
What? I'm not trying to sign into Google

**Comment by sgallag-insta** [comment]
I also encountered this issue. Looks like it is related to the GPU:
```
(node:4939) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/opt/geforcenow-electron/resources/app/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
(Use `geforcenow --trace-warnings ...` to show where the warning was created)
(node:4939) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
GPU at BusId 0x2 doesn't have a supported video decoder
[4939:0715/224924.539910:ERROR:gpu_process_host.cc(975)] GPU process exited unexpectedly: exit_code=136
GPU at BusId 0x2 doesn't have a supported video decoder
[4939:0715/224924.922632:ERROR:gpu_process_host.cc(975)] GPU process exited unexpectedly: exit_code=136
GPU at BusId 0x2 doesn't have a supported video decoder
[4939:0715/224925.351556:ERROR:gpu_process_host.cc(975)] GPU process exited unexpectedly: exit_code=136
GPU at BusId 0x2 doesn't have a supported video decoder
[4939:0715/224925.964275:ERROR:gpu_process_host.cc(975)] GPU process exited unexpectedly: exit_code=136
GPU at BusId 0x2 doesn't have a supported video decoder
[4939:0715/224926.562377:ERROR:gpu_process_host.cc(975)] GPU process exited unexpectedly: exit_code=136
GPU at BusId 0x2 doesn't have a supported video decoder
[4939:0715/224927.181274:ERROR:gpu_process_host.cc(975)] GPU process exited unexpectedly: exit_code=136
[5090:0715/224927.188489:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is 
[5090:0715/224927.241522:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```
In my case, switching from dedicated to integrated graphics was able to bypass the issue.

**Comment by Hi-Phile** [comment]
FYI, I just installed the gfn-electron today from AUR, it does load and able to login with existing gfn account.  Thus, I did not encounter this error.
Arch Linux  5.19.10-arch1-1
Resolution: 1920x1080 @ 60Hz
DE: Xfce4 4.16.1
WM: Xfwm4 (X11)

![image](https://user-images.githubusercontent.com/35350630/193395001-bcc38640-2e72-4bce-a7de-80c5dd5ccaca.png)

**Comment by drod3763** [comment]
I have the same issue. Might be a GPU issue as I get the below error in the terminal:

```
Using user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.101 Safari/537.36
Process arguments: /opt/geforcenow-electron/geforcenow-electron
(node:516939) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/opt/geforcenow-electron/resources/app/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (node:events:642:26)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
(Use `geforcenow --trace-warnings ...` to show where the warning was created)
(node:516939) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[516939:1209/111459.446614:ERROR:gpu_process_host.cc(966)] GPU process exited unexpectedly: exit_code=256
[516939:1209/111459.571947:ERROR:gpu_process_host.cc(966)] GPU process exited unexpectedly: exit_code=256
[516939:1209/111459.695597:ERROR:gpu_process_host.cc(966)] GPU process exited unexpectedly: exit_code=256
[516939:1209/111459.768807:ERROR:gpu_process_host.cc(966)] GPU process exited unexpectedly: exit_code=256
[516939:1209/111459.845197:ERROR:gpu_process_host.cc(966)] GPU process exited unexpectedly: exit_code=256
[516939:1209/111459.925738:ERROR:gpu_process_host.cc(966)] GPU process exited unexpectedly: exit_code=256
[517093:1209/111459.928963:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is 
[517093:1209/111459.949861:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

**Comment by nitanmarcel** [comment]
@hmlendea I'm also using Google as my authentication method on GFNow, and I've found the following firefox user agent allowing me to log in with google.


`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0`

I wanted to create a PR to add it as an argument for the user agent, but since firefox is not supported on GFNow (at least for me) I suppose it could be automatically switched to it when the google login page is being displayed and then back to the default one on the GFNow page. No idea how to do that tho :)

**Comment by hmlendea** [comment]
Is this issue still affecting the latest supported versions?

**Comment by AnimaKitt** [comment]
The solution I found, on Arch using the Aur (found this solution AFTER removing Snap version, have not attempted with it tho may also work.. ) I went to use google sign in, says unsupported browser, i hit learn more. from there was able to sign into my google account then i went back to unsupported browser page prior, hit big blue try again option and Now I am logged in. hope this helps someone. Good Luck!

**Comment by hmlendea** [comment]
Please re-open if this issue still affects the latest version of this app.
