### ISSUE TITLE
[BUG] [old hardware] Input delay (possibly unsuported gpu)

### ISSUE THREAD

**Issue by CheesyChocolate** [hmlendea/gfn-electron#192]
### Describe the bug

# version 1.10 from AUR
* no problem. minimum input delay everything works as it should
* Terminal output during lunch
```
$ geforcenow
Using user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.101 Safari/537.36
Process arguments: /opt/geforcenow-electron/geforcenow-electron
(node:4944) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/opt/geforcenow-electron/resources/app/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (node:events:642:26)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
(Use `geforcenow --trace-warnings ...` to show where the warning was created)
(node:4944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Game streaming mode state changed to: true
Fullscreen state changed to: true
[4975:0612/204755.542399:ERROR:vaapi_wrapper.cc(2545)] vaPutSurface failed, VA error: unknown libva error
[4975:0612/204755.542731:ERROR:vaapi_video_decode_accelerator.cc(287)] Failed putting surface into pixmap
[4994:0612/204755.553063:ERROR:h264_decoder_impl.cc(336)] avcodec_send_packet error: -1094995529
Game streaming mode state changed to: false
Fullscreen state changed to: false
```
# version 1.11 from AUR and git version build by NPM
* while in game, experience input delay up to 2 second (sometimes immediately after firing up the game, sometime after a while)
* Terminal output during lunch
```
$ npm start

> geforcenow-electron@1.11.0 start
> electron .

Using user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.101 Safari/537.36
Process arguments: /home/suren/opt/gfn-electron/node_modules/electron/dist/electron,.
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[1686:0612/204224.446881:FATAL:gpu_init.cc(542)] Passthrough is not supported, GL is egl, ANGLE is
[1649:0612/204224.527795:ERROR:gpu_process_host.cc(943)] GPU process exited unexpectedly: exit_code=5
(node:1649) UnhandledPromiseRejectionWarning: Error: Could not connect
    at Socket.onerror (/home/suren/opt/gfn-electron/node_modules/discord-rpc/src/transports/ipc.js:32:16)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:1649) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[1715:0612/204224.775536:FATAL:gpu_init.cc(542)] Passthrough is not supported, GL is egl, ANGLE is
[1649:0612/204224.786803:ERROR:gpu_process_host.cc(943)] GPU process exited unexpectedly: exit_code=5
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[1723:0612/204225.030078:FATAL:gpu_init.cc(542)] Passthrough is not supported, GL is egl, ANGLE is
[1649:0612/204225.038045:ERROR:gpu_process_host.cc(943)] GPU process exited unexpectedly: exit_code=5
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[1693:0612/204225.375386:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[1649:0612/204313.446540:ERROR:cert_verify_proc_builtin.cc(677)] CertVerifyProcBuiltin for cdn.netmera-web.com failed:
----- Certificate i=2 (CN=NextDNS Blockpage CA,O=NextDNS Inc.) -----
ERROR: No matching issuer found


[1689:0612/204313.448431:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -202
[1649:0612/204313.460227:ERROR:cert_verify_proc_builtin.cc(677)] CertVerifyProcBuiltin for www.googletagmanager.com failed:
----- Certificate i=2 (CN=NextDNS Blockpage CA,O=NextDNS Inc.) -----
ERROR: No matching issuer found


[1689:0612/204313.462532:ERROR:ssl_client_socket_impl.cc(992)] handshake failed; returned -1, SSL error code 1, net_error -202
Game streaming mode state changed to: true
Fullscreen state changed to: true
Game streaming mode state changed to: false
Fullscreen state changed to: false
```

### To Reproduce

1. use geforcenow electron version 1.10 without problem
2.  remove geforcenow electron 1.10 package ($ yay -Rns geforcenow-electron)
3.  remove ~/.config/GeForce NOW
4. clean install version 1.11 from aur (or git version using npm)
5. firing up geforcenow electron 1.11 and a game
6. input delay

### Operating System

Arch Linux

### Desktop Environment

dwm

### Display Server

X11

### Installation method

AUR (1.10 and 1.11) and npm (git version)

### Version

1.10 and 1.11 and git (Merge: bb02d9a e39f521)

### Is this a fresh install of the app or an update from a past version?

all version are tested on fresh clean install

### Did this issue appear right away upon installation/updating, or spontaneously?

Yes after update to version 1.11

### Additional context

I understand that my old hardware is not supported and I don't expect to. I will keep using version 1.10 

I put this here for others information. I do not need the support of this new version on my old hardware.

Thank you @hmlendea for your great creation

**Comment by Chaussettes99** [comment]
I can't provide any logs right now but I can confirm that I also get the input slowdown on version 1.11 appimage. Version 1.10 performed just fine with very minimal input delay. I can get around this by just using the 1.10 appimage for now.

I also have similarly older hardware but it does handle version 1.10 just fine
Debian 12 Bookworm (GNOME Desktop)
Pentium E5300 (2)
NVIDIA GeForce GT 635
4.00 GB of RAM

**Comment by hmlendea** [comment]
I'm closing this for now so that we can centralise all input lag issues on #162
