### ISSUE TITLE
[BUG] Using Spoof-Args has no effect

### ISSUE THREAD

**Issue by Coki91** [hmlendea/gfn-electron#252]
### Describe the bug

Launching gfn-electron through a command line with spoof arguments has no effect, apparently from the console,the user agent is picked up before the arguments process, and other type of arguments do have effect

Logs
`[USER@USER-pc ~]$ geforcenow --spoof-windows --trace-warnings --disable-rpc
Using user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Process arguments: /opt/geforcenow-electron/geforcenow-electron,--spoof-windows,--trace-warnings,--disable-rpc
[102516:0817/034833.532324:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[102516:0817/034833.532587:ERROR:select_file_dialog_linux_portal.cc(286)] Failed to read portal version property
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
libva error: /usr/lib/dri/iHD_drv_video.so init failed
(node:102516) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'webContents')
    at Object.unregisterAll (/opt/geforcenow-electron/resources/app/node_modules/electron-localshortcut/index.js:83:17)
    at App.<anonymous> (/opt/geforcenow-electron/resources/app/scripts/main.js:161:25)
    at App.emit (node:events:514:28)
    at App.<anonymous> (/opt/geforcenow-electron/resources/app/scripts/main.js:166:9)
    at App.emit (node:events:526:35)
    at emitUnhandledRejectionWarning (node:internal/process/promises:201:15)
    at processPromiseRejections (node:internal/process/promises:297:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:102516) TypeError: Cannot read properties of undefined (reading 'webContents')
    at Object.unregisterAll (/opt/geforcenow-electron/resources/app/node_modules/electron-localshortcut/index.js:83:17)
    at App.<anonymous> (/opt/geforcenow-electron/resources/app/scripts/main.js:161:25)
    at App.emit (node:events:514:28)
    at App.<anonymous> (/opt/geforcenow-electron/resources/app/scripts/main.js:166:9)
    at App.emit (node:events:526:35)`

### To Reproduce

1. Open Console
2. Launch gfn-electron with "geforcenow --spoof-windows"/"geforcenow --spoof-chromeos"

### Screenshots

![image](https://github.com/user-attachments/assets/a1cbc4f0-6d96-4f62-89db-3b36b7072921)

### Operating System

Archlinux

### Desktop Environment

LXQT 2.0.0

### Display Server

X11

### Installation method

Any (Tested all install methods including manual)

### Version

2.1.2

### Is this a fresh install of the app or an update from a past version?

Fresh

### Did this issue appear right away upon installation/updating, or spontaneously?

Yes, right after installation

### Additional context

Im trying to change the keyboard layout, read in the Github spoofing the UA would allow me to, and was stopped in track due to this issue

**Comment by orion715** [comment]
Unfortunately this is the new norm, Nvidia changed some things and the spoofing no longer works.
